name: Check file hashes

on:
  push:
    branches: '**'

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2

      - name: Check file hashes
        run: |
          expected_hash="6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"

          # Find all files in the repository
          files=$(find . -type f)

          # Loop over each file
          for file in $files; do
            # Calculate the hash of the file
            actual_hash=$(sha256sum $file | cut -d' ' -f1)

            # Compare the calculated hash with the expected hash
            if [ "$actual_hash" = "$expected_hash" ]; then
              echo "File hash matches: $file"
            else
              echo "File hash does not match: $file"
              exit 1
            fi
          done
